apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-optimized
  namespace: bench-artemis
  labels:
    benchmark.ninefinger9.io/broker: artemis
    benchmark.ninefinger9.io/mode: optimized
spec:
  version: 2.44.0
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    clustered: false
    requireLogin: true
    journalType: aio
    storage:
      size: 20Gi
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi
  acceptors:
    - name: amqp
      port: 5672
      protocols: amqp
      expose: false
  brokerProperties:
    - global-max-size=1024m
    - journal-buffer-timeout=3333333
    - journal-file-size=10485760
    - address-setting.#.redelivery-delay=0
    - address-setting.#.max-delivery-attempts=5
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: artemis-optimized-benchmark-events
  namespace: bench-artemis
  labels:
    benchmark.ninefinger9.io/broker: artemis
    benchmark.ninefinger9.io/mode: optimized
spec:
  applyToCrNames:
    - artemis-optimized
  addressName: benchmark.events
  queueName: benchmark.events
  routingType: anycast
  queueConfiguration:
    durable: true
